config/routes.rb
Rails.application.routes.draw do
  get 'books/new'

  root :to => 'homes#top' # root_path

  post 'books' => 'books#create'
  get '/books' => 'books#index', as: 'index_book'
  get 'books/:id' => 'books#show', as: 'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end


  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'


  end




  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this book from being saved:
 <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
<% end %>


<%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>
 <br>

 <%= f.submit 'Update Book' %>

<% end %>

<p>
<%= link_to "Show", book_path(@book.id) %> |
<%= link_to "Back", index_book_path %>
</p>

app/views/books/index.html.erb
<!--一覧ページ-->

<table>
 <h1>Books</h1>

  <span class="he1">title</span>
  <span class="he2">body</span>
  <span class="he3">command</span>


 <p>
<% @books.each do |book| %>
 <span class="title"><%= book.title %></span>
 <span class="body"><%= book.body %></span>

 <span class ="tag">
  <%= link_to 'Show' ,book_path(book.id) %>
 </span>
 <span class ="tag">
  <%= link_to 'Edit' ,edit_book_path(book.id) %>
  </span>
 <span class ="tag">
  <%= link_to 'Destroy' ,destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %>
  </span>
 </br>

<% end %>

 </p>

</table>


<!--ここから新規投稿-->


<h1>New book</h1>
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this book from being saved:
 <ul class="errors">
  <% @book.errors.full_messages.each do |message| %>
   <li class="er"><%= message %></li>
   <% end %>
 </ul>
<% end %>



<%= form_with model: @book, url: '/books', method: :post do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>

 <br>
 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this book from being saved:
 <ul>
  <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
<% end %>



<%= form_with model: @book, url: '/books', method: :post do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="show">
<h4>Title:</h4>
<p><%= @book.title %></p>

<h4>Body:</h4>
<p><%= @book.body %></p>

<p>
<%= link_to "Edit", edit_book_path(@book.id) %> |
<%= link_to "Back", index_book_path %>
</p>
</div>

app/views/homes/top.html.erb
<h1>ようこそ　Bookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます
</p>

<div class="linktext">
<%= link_to 'start','/books' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="text-success">
    <%= flash[:notice] %>
    </div>

    <%= yield %>




  </body>
</html>